import { draftMode } from "next/headers"
import  PreviewSuspense  from "../../components/PreviewSuspense";
import Banner from '@/components/Banner'
import PostSection from "@/components/PostSection";



export const metadata = {
  title: 'MyBlog',
  description: 'Generated by create next app',
}

export default function Home() {
  const { isEnabled } = draftMode();

  if (isEnabled) {
    return (<PreviewSuspense fallback="Loading...">
      <>preview</>
    </PreviewSuspense>)
  }
  else {
    return (
      // <main>
      //   <h1>My Blog Post</h1>
      //   <p>Draft Mode is currently disable</p>
      // </main>
      <>
      <Banner/>
      <PostSection/>
      </>
    );
  }

}
